[package]
name = "murrelet_gui"
version = "0.1.2"
edition = "2021"

[features]

[dependencies]
murrelet_gui_derive = { path = "../murrelet_gui_derive/" }

thiserror = "2.0.11"


[[example]]
name = "tests"
path = "examples/tests.rs"
